language: cpp
os: linux
dist: trusty

install:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  - ./start.sh
