---
- name: prepare apt repositories for nodejs
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  become: true

- name: prepare apt repositories for yarn 1
  shell: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  become: true

- name: prepare apt repositories for yarn 2
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  become: true

- name: install deps 1
  apt:
    name={{ item }}
    state=present
  with_items:
    - rustc
    - cargo
    - nodejs
  tags: pkg-install
  become: true

- name: install deps 2
  apt:
    name={{ item }}
    state=present
  with_items:
    - yarn
  tags: pkg-install
  become: true
